// util_assert_exception.lzz
//

void throwAssertException(char const *exp, char const *file, int line)
{
   std::string path, name;
   file_op::getPathAndName(file, path, name);
   throw std::runtime_error(Message("%:%: unexpected %") << name << line << exp);
}

#hdr
#define AssertException(exp) (void)((exp) || (throwAssertException(#exp, __FILE__, __LINE__), 0))
#end

#src
#include <util_file_op.h>
#include <util_message.h>
#include <stdexcept>
#end
